#!/usr/bin/env python3
"""Colorize your output using RegEx"""

import chromaterm
import chromaterm.misc

if __name__ == '__main__':
    chromaterm.misc.write_default_config()  # Write default config if not there
    chromaterm.main(chromaterm.args_init())
